/*
 * File: \src\internal\instance\types.ts
 * Project: flish-app
 * Created Date: Wednesday December 8th 2021
 * Author: Julien Cagniart
 * -----
 * Last Modified: 08/12/2021 18:33
 * Modified By: Julien Cagniart
 * -----
 * Copyright (c) 2021 Julien - juliencagniart40@gmail.com
 * -----
 * _______ _ _      _                 _             
(_______) (_)    | |               | |            
 _____  | |_  ___| | _           _ | | ____ _   _ 
|  ___) | | |/___) || \         / || |/ _  ) | | |
| |     | | |___ | | | |   _   ( (_| ( (/ / \ V / 
|_|     |_|_(___/|_| |_|  (_)   \____|\____) \_/  
                                                   
 * Purpose of this file : 
 *  Link to documentation associated with this file : (empty) 
 */

export interface Instance {
  /** The Unique ID of the extension generated by nanoID */
  instanceID: string;
  /** A name choosen by the user. This name will be shown in the interface and searchable */
  name: string;
  /** The keyboard shortcut to fire up any extension (e.g CTRL+ALT+A) */
  keyboard?: string;
  /** The id of the linked extension */
  extensionID: string;
}
import { envVariables } from "../../internal/extension/types";
export interface updateEnvVariables extends envVariables {
  /** The value to update */
  value: string | number | boolean;
}
